// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Mc sprite":return img`
..............................
..............................
..............................
..............................
..............................
..............................
......ffffffffff..............
......ff4444444ff.............
......f2f444444f2f............
......f22fffffff2f............
......f22fffffff2f............
......f22fffffff2f............
......f22fffffff2f............
......f22fffffff2f............
......f22fffffff2f............
......f22fffffff2f............
.......f2f444444ff............
........ffffffffff............
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
